export const INJECTION_TOKENS = {
  IRecruitYearRepository: Symbol('IRecruitYearRepository'),
  IUserRepository: Symbol('IUserRepository'),
  ICompanyRepository: Symbol('ICompanyRepository'),
  IDepartmentRepository: Symbol('IDepartmentRepository'),
  IInterviewerRepository: Symbol('IInterviewerRepository'),
  IUniversityRepository: Symbol('IUniversityRepository'),
  IFacultyRepository: Symbol('IFacultyRepository'),
  IDeviationValueRepository: Symbol('IDeviationValueRepository'),
  IUniversityRankRepository: Symbol('IUniversityRankRepository'),
  IEducationalBackgroundRepository: Symbol('IEducationalBackgroundRepository'),
  IEventLocationRepository: Symbol('IEventLocationRepository'),
  IEventMasterRepository: Symbol('IEventMasterRepository'),
  IEventRepository: Symbol('IEventRepository'),
  ISearchConditionRepository: Symbol('ISearchConditionRepository'),
  IAuthUserRepository: Symbol('IAuthUserRepository'),
} as const;
